site_name: Sigbla docs
docs_dir: content
#site_url: TODO
#repo_url: TODO

nav:
  - 'index.md'
  - 'tables.md'
  - 'views.md'

theme:
  name: material
  features:
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
