site_name: Sigbla App Docs
site_author: Christian Felde
copyright: Copyright 2019-2024, Christian Felde
docs_dir: content
site_url: https://sigbla.app/docs/
repo_url: https://github.com/sigbla/sigbla-app

nav:
  - 'index.md'
  - 'tables.md'
  - 'columns.md'
  - 'rows.md'
  - 'cells.md'
  - 'ranges.md'
  - 'views.md'
  - 'functions.md'
  - 'charts.md'
  - 'widgets.md'
  - 'math.md'
  - 'table_subscriptions.md'
  - 'view_subscriptions.md'
  - 'view_resources.md'
  - 'view_extensions.md'
  - 'concurrency.md'
  - 'batching.md'
  - 'utils.md'

# TODO: cellview sizing (with colspan, listeners etc)

theme:
  name: material
  features:
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - path: js/static1.js
    defer: true
