site_name: Sigbla docs
docs_dir: content
#site_url: TODO
#repo_url: TODO

nav:
  - 'index.md'
  - 'tables.md'
  - 'columns.md'
  - 'rows.md'
  - 'cells.md'
  - 'views.md'
  - 'subscriptions.md'
  - 'concurrency.md'
  - 'charts.md'
  - 'user_input.md'
  - 'math.md'
  - 'utils.md'

theme:
  name: material
  features:
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
